ignore:
  - "**/*.json"
  - "**/*.md"
  - "**/*.mod"
  - "**/*.sum"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*_test.go"
  - "**/Dockerfile"
  - "**/LICENSE"
  - "**/Makefile"
  - ".github/"
  - ".rules/"
  - ".vscode/"
  - "coverage/"
  - "dist/"
  - "docs/"
  - "output/"
  - "scripts/"

codecov:
  require_ci_to_pass: true
  branch: main

coverage:
  status:
    project:
      default:
        enabled: false
        target: auto
        threshold: 0.25% # Optional: fail only if coverage drops more than this
    patch:
      enabled: true
      target: auto
      threshold: 0.25% # Optional: fail only if coverage drops more than this
    changes:
      enabled: true
      target: auto
      threshold: 0.25% # Optional: fail only if coverage drops more than this
