ignore:
  - "**/*.json"
  - "**/*.md"
  - "**/*.mod"
  - "**/*.sum"
  - "**/*.yaml"
  - "**/*.yml"
  - "**/*_test.go"
  - "**/Dockerfile"
  - "**/LICENSE"
  - "**/Makefile"
  - ".github/"
  - ".rules/"
  - ".vscode/"
  - "coverage/"
  - "dist/"
  - "docs/"
  - "output/"
  - "scripts/"

codecov:
  require_ci_to_pass: true
  branch: main

coverage:
  status:
    project:
      app:
        target: auto
        paths: "!tests/"
      tests:
        target: auto
        paths: "tests/"
    patch:
      enabled: true
      target: auto
      threshold: 0.25%
      only_pulls: true
    changes:
      enabled: true
      target: auto
      threshold: 0.25%
      only_pulls: true
